### ISSUE TITLE
SyntaxError: Unexpected token a in JSON at position 0

### ISSUE THREAD

**Issue by callegyllen** [testthedocs/vscode-vale#5]
Hi,
I get this error message when I save an adoc file. 

`SyntaxError: Unexpected token a in JSON at position 0`

What does it mean?
How do I solve it?

![ValeSyntaxError](https://user-images.githubusercontent.com/28574383/66035481-8331f100-e50b-11e9-9234-71afd2feb656.png)

Thanks for help in advance :)

**Comment by callegyllen** [comment]
![ValeSyntaxError2](https://user-images.githubusercontent.com/28574383/66035742-ffc4cf80-e50b-11e9-852a-1570746db840.png)

**Comment by ChrisChinchilla** [comment]
@callegyllen  I have often experienced this myself, and I'm not always sure what it relates to. Is it only ever with Asciidoc files?

**Comment by ChrisChinchilla** [comment]
@callegyllen I am looking into adding Asciidoc support right now, which is why I think you're getting this error.

**Comment by callegyllen** [comment]
Yay!! Fantastic. Sorry for not replying to your first comment.

Did some changes in other types of files (md, yaml, json) and I didn't get the same error message.

**Comment by ChrisChinchilla** [comment]
@callegyllen So the last release should have fixed this.
