### ISSUE TITLE
v2.0.0-beta compatibility ?

### ISSUE THREAD

**Issue by Jc-L** [testthedocs/vscode-vale#6]
Is the extension working with vale 2.0.0-beta ? The extension is of no effect on my installation, but I would like to ensure issue is not related to a known compatibility issue.

**Comment by ChrisChinchilla** [comment]
Hmm, hadn't actually thought about it yet actually. I'm also speaking with Vale dev about extensions generally, so watch this space.

**Comment by brandonkal** [comment]
I installed v2.0.0-beta. It was working initially. Now the extension no longer works. Additionally, I am seeing this:
```
command 'vale.lintWorkspace' not found
```
A complete uninstall and re-install of the extension did not help.

**Comment by ChrisChinchilla** [comment]
@brandonkal As mentioned above, there is no support right now

**Comment by ChrisChinchilla** [comment]
As far as I can tell, running with Vale 2.0 now seems to be working, let me know if that's not true.
