### ISSUE TITLE
configure alternative binary name and project-local search path

### ISSUE THREAD

**Issue by nkuehn** [testthedocs/vscode-vale#7]
Hi, here's the issue you ask for in the README :-) 

We have the following setup:  Inside the company we provide a preconfigured vale with styles and config as an NPM package to be pulled into all projects that have documentation as a dev dependency. 

It provides a vale command prefixed with the company name (e.g. `mycompany-vale`) and projects should use the one in the node_modules instead of manual installation so everbody is on the exact same setup.    

I can imagine it to work great with the following two configuration additions:

1. be able to configure / override the executable name "vale"  globally and/or per VSCode workspace
2. be able to configure a relative search path inside the project / workspace root instruct the plugin to first try  './node_modules/.bin/'  before trying the global PATH.   Alternatively make the pattern explicit and "magically" support NPM provided binaries if present. 

What do you think? Is that a sensible approach to make it configurable?   If yes, we could try to contribute something.

**Comment by ChrisChinchilla** [comment]
Err, I'm not sure if I completely understand the setup, or the approach, but I do appreciate that currently passing vale config around a company or project is a bit fiddly.

I feel like thanks to VSC's concept of projects and workspaces, this should be reasonably easy, but we'd have to test it. You could also possibly alias commands locally maybe 🤔

**Comment by nkuehn** [comment]
sorry for confusing you  - aliasing the command doesn't really work because it's happening in the OS shell(s), but execFile()  does not launch a shell around the command it starts.   

You're right that being able to configure the executable "name or path" string and leveraging workspace config for the rest could be a feasible MVP approach, we'll take a look.
